version: '3.8'

services: 
  db: 
    build: ./database
    restart: always
    env_file:
      - ./config/db.env
    ports:
      - "3306:3306"
    networks: 
      - docker-network-compose
  api:
    depends_on:
      - db
    build: ./api
    restart: always
    ports: 
      - "3000:3000"
    networks: 
      - docker-network-compose

networks:
  docker-network-compose: